### PR TITLE
rspheaders added

### PR DESCRIPTION
**Pull request by mridhuljp**
Adding support for response headers in haproxy. The default header was supporting only request headers. Hardering parameters like HSTS needs response headers in haproxy

### CODE REVIEW

**Comment by mridhuljp** [comment]
@geofffranks @shinji62 @drnic

**Comment by shinji62** [comment]
Why this header are not send by the application ?

**Comment by mridhuljp** [comment]
Idea was to make use of front-end haproxy to handle response headers rather than making apps to send the headers. If we have large number of applications deployed in cloudfoundry, we found its easy to set the header in haproxy. Do you see a performance / maintenance impact with the change ? just curious

**Comment by shinji62** [comment]
No I was just wondering.

**Comment by geofffranks** [comment]
Can you add release notes summarizing this feature in markdown format to `ci/release_notes.md`?  Our release building pipeline looks at that file for the github release.

Otherwise, I'm fine with this

**Comment by mridhuljp** [comment]
@geofffranks : Done

**Comment by geofffranks** [comment]
thanks. Looks like there are merge conflicts now though? can you resolve those and i'll merge + release?

**Comment by mridhuljp** [comment]
@geofffranks : Thanks for your time, I've resolved the merge conflicts.

**Comment by geofffranks** [comment]
Final release 8.0.3 created today with this in it.

**Pull request merged**
